hydra:
  job:
    chdir: False

batch_size: 4
valid_batch_size: 8
epochs: 3
num_workers: 4
lr: 2e-5
max_length: 1024
stride: 256
model_name: "microsoft/deberta-v3-large"
hidden_dropout_prob: 0.1
layer_norm_eps: 1e-7
gradient_accumulation_steps: 2
gradient_checkpointing_enable: False
warmup_ratio: 0.1
max_grad_norm: 5.0
seed: 42
device: "cuda"
multi_gpu: True
use_wandb: True
project_name: "pii-kaggle"
metadata_path: "../data/pii_texts.csv"
output_dir: "../output/"
repo_id: ""
freeze: False
start_freeze_layer: 0
end_freeze_layer: 6
threshold: 0.9
llrd: 1
use_external_data: True
train_fold: True
train_whole_dataset: False
