hydra:
  job:
    chdir: False

batch_size: 2
valid_batch_size: 4
epochs: 3
num_workers: 2
lr: 1e-5
max_length: 1024
stride: 256
model_name: "microsoft/deberta-v3-large"
hidden_dropout_prob: 0.1
layer_norm_eps: 1e-7
gradient_accumulation_steps: 4
gradient_checkpointing_enable: False
warmup_ratio: 0.1
max_grad_norm: 10.0
weight_decay: 0.01
seed: 42
use_wandb: True
project_name: "pii-kaggle"
metadata_path: "../data/pii_texts.csv"
output_dir: "../output/"
repo_id: ""
freeze: False
start_freeze_layer: 0
end_freeze_layer: 6
threshold: 0.9
save_other_threshold: False
llrd: 1
use_external_data: True
external_data_name: "mpware"
random_masking: False # Whether to randomly mask 'O' tokens in the input
masking_ratio: 0.4 # Probability of masking 'O' tokens in the input
train_fold: True
num_folds: 4
fold: 0
train_whole_dataset: False
visualize: True
upload_models: True
add_new_line_token: True
merge_token_preds: True
downsample_dataset: False
downsample_ratio: 0.4
pooling: "normal"
