hydra:
  job:
    chdir: False

batch_size: 16
valid_batch_size: 16
epochs: 3
num_workers: 0
lr: 2e-5
max_length: 512
model_name: "microsoft/deberta-v3-base"
hidden_dropout_prob: 0.1
layer_norm_eps: 1e-7
gradient_accumulation_steps: 1
gradient_checkpointing_enable: False
warmup_ratio: 0.1
max_grad_norm: 10.0
seed: 42
device: "cuda"
multi_gpu: False
use_wandb: True
project_name: "pii-kaggle"
metadata_path: "../data/pii_texts.csv"
output_dir: "../output/"
repo_id: ""
freeze: False
start_freeze_layer: 0
end_freeze_layer: 6
llrd: 1
use_external_data: False
